#' Weighted log-rank test
#'
#' Non-parametric weighted (or unweighted) log-rank test of differences
#' between two groups, following Xie and Liu (2005) and Singh et al.
#' (2014). Compares the true `G_rho` test statistic to a reference
#' distribution generated by permutation, bootstrap, or simulation.
#'
#' @param grouped_data A data frame with columns `Concentration`,
#'   `Censored`, `Site`, and `Dataset` (group identifier).
#' @param comp_group Identifier of the *comparison* group. Defaults to
#'   the second level of `Dataset`.
#' @param rho Non-negative real number. Weight exponent on the pooled
#'   survival estimator (Singh et al., 2014); `0` is the unweighted
#'   log-rank statistic.
#' @param method Reshuffling method: `"perm"` (sample without
#'   replacement), `"boot"` (with replacement), or `"sim"` (simulate
#'   from the marginal class proportions).
#' @param boots Number of randomisations.
#' @param alternative One of `"two.sided"`, `"greater"`, or `"less"`,
#'   referring to the comparison group `comp_group`.
#' @return A list with elements `G_test` (true statistic), `boot_G`
#'   (vector of randomised statistics), `p.val`, and `rho`.
#' @export
log_rank <- function(grouped_data,
                     comp_group = NULL,
                     rho = 1,
                     method = "perm",
                     boots = 1000,
                     alternative = "two.sided") {
  method <- rlang::arg_match(method, c("perm", "boot", "sim"))
  alternative <- rlang::arg_match(alternative, c("two.sided", "greater", "less"))

  if (is.null(comp_group)) {
    grps <- levels(factor(grouped_data$Dataset))
    ref <- grouped_data |>
      dplyr::filter(.data$Dataset == grps[1]) |>
      dplyr::select(-"Dataset")
    comp <- grouped_data |>
      dplyr::filter(.data$Dataset == grps[2]) |>
      dplyr::select(-"Dataset")
  } else {
    ref <- grouped_data |>
      dplyr::filter(.data$Dataset != comp_group) |>
      dplyr::select(-"Dataset")
    comp <- grouped_data |>
      dplyr::filter(.data$Dataset == comp_group) |>
      dplyr::select(-"Dataset")
  }

  test_G <- G_rho(ref_data = ref, comp_data = comp, rho = rho)
  sim_G <- purrr::map_dbl(
    seq_len(boots),
    \(i) sim_G_rho(grouped_data, rho = rho, method = method)
  )

  p.val <- switch(
    alternative,
    two.sided = sum(abs(sim_G) >= abs(test_G)) / boots,
    greater   = sum(sim_G >= test_G) / boots,
    less      = sum(sim_G <= test_G) / boots
  )

  list(G_test = test_G, boot_G = sim_G, p.val = p.val, rho = rho)
}
